services:
  postgres:
    build:
      context: ./dbdockerfile
    ports:
      - 5433:5432
  backend:
    build:
      context: ./backend
    ports:
      - 3000:3000
    links:
      - "postgres"
    depends_on:
      - postgres